// Password hashing via WebCrypto PBKDF2-SHA-256.
//
// Why PBKDF2 and not Argon2id/scrypt: the Workers runtime caps
// crypto.subtle PBKDF2 at 100k iterations and the free plan caps CPU at
// 10ms/request — pure-JS/WASM scrypt or Argon2 with sane params blows that
// budget, while native PBKDF2 fits. 100k iterations is below the OWASP
// recommendation (600k for SHA-256); accepted trade-off for a closed,
// invite-only instance with login rate limiting. Revisit if the runtime cap
// is lifted.
//
// This module is runtime-agnostic (Workers + Node ≥20): scripts under
// /scripts import it directly, so hashes generated by the seed/CLI match
// what the Worker verifies.

const ALGORITHM = 'pbkdf2-sha256'
const ITERATIONS = 100_000
const SALT_BYTES = 16
const KEY_BYTES = 32

export async function hashPassword(password: string): Promise<string> {
  const salt = crypto.getRandomValues(new Uint8Array(SALT_BYTES))
  const hash = await derive(password, salt, ITERATIONS)
  return `${ALGORITHM}$${ITERATIONS}$${toBase64(salt)}$${toBase64(hash)}`
}

export async function verifyPassword(password: string, stored: string): Promise<boolean> {
  const parts = stored.split('$')
  if (parts.length !== 4) return false
  const [algorithm, iterationsRaw, saltB64, hashB64] = parts as [string, string, string, string]
  const iterations = Number(iterationsRaw)
  if (algorithm !== ALGORITHM || !Number.isInteger(iterations) || iterations < 1) return false
  const expected = fromBase64(hashB64)
  const actual = await derive(password, fromBase64(saltB64), iterations)
  return timingSafeEqual(expected, actual)
}

/**
 * Same cost as verifyPassword, discarded result. Login calls this when the
 * username does not exist so both branches take the same ~100k-iteration
 * detour — otherwise the response time (≈1ms vs ≈50ms) enumerates accounts.
 */
export async function burnPasswordTime(password: string): Promise<void> {
  await derive(password, DUMMY_SALT, ITERATIONS)
}

// Fixed salt on purpose: this derivation is never stored or compared, it only
// has to cost the same as a real one.
const DUMMY_SALT = new Uint8Array([
  0x67, 0x6f, 0x6f, 0x64, 0x63, 0x68, 0x61, 0x74, 0x2d, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x2d, 0x73,
])

async function derive(password: string, salt: Uint8Array, iterations: number): Promise<Uint8Array> {
  const key = await crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(password),
    'PBKDF2',
    false,
    ['deriveBits'],
  )
  const bits = await crypto.subtle.deriveBits(
    { name: 'PBKDF2', hash: 'SHA-256', salt: salt as BufferSource, iterations },
    key,
    KEY_BYTES * 8,
  )
  return new Uint8Array(bits)
}

function timingSafeEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false
  let diff = 0
  for (let i = 0; i < a.length; i++) diff |= (a[i] as number) ^ (b[i] as number)
  return diff === 0
}

function toBase64(bytes: Uint8Array): string {
  let binary = ''
  for (const byte of bytes) binary += String.fromCharCode(byte)
  return btoa(binary)
}

function fromBase64(value: string): Uint8Array {
  const binary = atob(value)
  const bytes = new Uint8Array(binary.length)
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i)
  return bytes
}
